version: '3.7'

services:
  app:
    hostname: "helfi-proxy.docker.so"
    container_name: "helfi-reverse-proxy-app"
    image: "nginx:stable-alpine"
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template:ro
    networks:
      - stonehenge-network
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.helfi-reverse-proxy-app.entrypoints=https"
      - "traefik.http.routers.helfi-reverse-proxy-app.rule=Host(`helfi-proxy.docker.so`)"
      - "traefik.http.routers.helfi-reverse-proxy-app.tls=true"
      - "traefik.http.services.helfi-reverse-proxy-app.loadbalancer.server.port=8080"
      - "traefik.docker.network=stonehenge-network"

    extra_hosts:
      - helfi-backend:host-gateway
networks:
  stonehenge-network:
    external: true
